Changes way of handling timeouts
applicaai/spring-boot-starter-temporal pull request #8
Opened 2021-01-14 16:08 UTC by SilverSheep

2021-01-15 11:09 UTC, bfugas requested changes

2021-01-19 14:01 UTC, SilverSheep commented on src/main/java/ai/applica/spring/boot/starter/temporal/annotations/ActivityStub.java
> +  String duration() default "PT0S";
As discussed - for now I'll leave it as it is

2021-01-19 14:01 UTC, SilverSheep commented on src/main/java/ai/applica/spring/boot/starter/temporal/processors/ActivityStubInterceptor.java
> +  private static final String defaultDuration = "PT0S";
done

2021-01-19 14:01 UTC, SilverSheep commented on src/main/java/ai/applica/spring/boot/starter/temporal/processors/ActivityStubInterceptor.java
> +      options.setStartToCloseTimeout(Duration.parse(duration));
As discussed - leaving it as it is

2021-01-19 14:02 UTC, SilverSheep commented on src/test/java/ai/applica/spring/boot/starter/temporal/samples/HelloPropertiesTest.java
> +    //    Duration scheduleToCloseTimeout = workflow.getScheduleToCloseTimeout();
Removed comments

2021-01-19 14:03 UTC, SilverSheep commented on src/test/java/ai/applica/spring/boot/starter/temporal/samples/apps/HelloProperties.java
> +      //      Activity.getExecutionContext().getInfo().getScheduleToStartTimeout();
I couldn't find a way to test it

2021-01-19 14:04 UTC, SilverSheep commented on src/test/resources/application.yml
> -      scheduleToCloseTimeoutUnit: SECONDS
Done

2021-01-19 14:18 UTC, bfugas commented on src/main/java/ai/applica/spring/boot/starter/temporal/annotations/ActivityStub.java
> +  String duration() default "PT0S";
:+1:

2021-01-19 14:18 UTC, bfugas commented on src/main/java/ai/applica/spring/boot/starter/temporal/processors/ActivityStubInterceptor.java
> +      options.setStartToCloseTimeout(Duration.parse(duration));
`!defaultDuration.equals(duration)` solves it :+1:

2021-01-19 14:20 UTC, bfugas approved these changes

2021-01-28 11:43 UTC, bfugas approved these changes

2021-01-29 08:10 UTC, merged